version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: techypark
      POSTGRES_USER: techypark
      POSTGRES_PASSWORD: ${DB_PASSWORD:-localdev123}
      POSTGRES_MULTIPLE_DATABASES: techypark_main,techypark_wordpress,techypark_analytics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U techypark"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-localdev123}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s

  backend:
    build: ./backend
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_URL: postgresql://techypark:${DB_PASSWORD:-localdev123}@postgres:5432/techypark_main
      REDIS_URL: redis://:${REDIS_PASSWORD:-localdev123}@redis:6379
      JWT_SECRET: ${JWT_SECRET:-dev-jwt-secret}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  adminer:
    image: adminer
    ports:
      - "8090:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
